"""
ALIA Avatar - Conversation Orchestrator
Ties together the visit flow FSM, LLM engine, RAG pipeline, and scoring.
"""
from collections.abc import AsyncIterator
from typing import Optional, Dict, Any, List
from uuid import uuid4
from datetime import datetime
from loguru import logger

from app.models.schemas import (
    VisitSession,
    ConversationMessage,
    ConversationMode,
    CompetenceLevel,
    VisitFormat,
    VisitStep,
    DoctorProfile,
    IntentType,
    SentimentType,
    StartSessionRequest,
    StartSessionResponse,
    ConversationRequest,
    ConversationResponse,
)
from app.conversation.visit_flow import VisitFlowEngine, create_session
from app.ai.llm_engine import LLMEngine
from app.ai.rag import rag_pipeline
from app.config import get_settings
from app.evaluation.scorer import VisitScorer


class ConversationOrchestrator:
    """Orchestrates the full ALIA conversation experience."""

    def __init__(self):
        self.llm = LLMEngine()
        self.scorer = VisitScorer()
        self.sessions: Dict[str, VisitSession] = {}
        self.flows: Dict[str, VisitFlowEngine] = {}
        self.conversation_histories: Dict[str, List[Dict[str, str]]] = {}

    async def start_session(self, request: StartSessionRequest) -> StartSessionResponse:
        """Start a new conversation session."""
        # Create session
        session = create_session(
            mode=request.mode,
            level=request.level,
            visit_format=request.visit_format,
            product_focus=request.product_focus,
            doctor_profile=request.doctor_profile,
            user_id=request.user_id,
        )

        # Create flow engine
        flow = VisitFlowEngine(session)

        # Initialize RAG
        rag_pipeline.initialize()

        # Store session data
        self.sessions[session.id] = session
        self.flows[session.id] = flow
        self.conversation_histories[session.id] = []

        # Greeting is generated by the LLM - no hardcoded script anywhere.
        # If the provider is unreachable, the error propagates to the API layer.
        greeting = await self._generate_greeting(session, request.mode)
        logger.info(f"Session {session.id} started: mode={request.mode.value}, level={request.level.value}, format={request.visit_format.value}")

        return StartSessionResponse(
            session_id=session.id,
            greeting=greeting,
            doctor_profile=session.doctor_profile,
            current_step=session.current_step,
            level=session.level,
        )

    async def start_session_stream(self, request: StartSessionRequest):
        """Create the session and stream the LLM greeting token by token.

        Yields (event_dict, final_StartSessionResponse_or_None) - the caller
        serializes events; the final response is yielded last, once the full
        greeting is known so it can be stored in the history.
        """
        session = VisitSession(
            mode=request.mode,
            level=request.level,
            visit_format=request.visit_format,
            product_focus=request.product_focus,
            doctor_profile=request.doctor_profile,
            user_id=request.user_id,
        )
        flow = VisitFlowEngine(session)
        rag_pipeline.initialize()
        self.sessions[session.id] = session
        self.flows[session.id] = flow
        self.conversation_histories[session.id] = []

        logger.info(f"Session {session.id} started: mode={request.mode.value}, level={request.level.value}, format={request.visit_format.value}")

        greeting = await self._generate_greeting(session, request.mode)

        response = StartSessionResponse(
            session_id=session.id,
            greeting=greeting,
            doctor_profile=session.doctor_profile,
            current_step=session.current_step,
            level=session.level,
        )
        return response

    async def stream_greeting(self, session: VisitSession, mode: ConversationMode) -> AsyncIterator[str]:
        """Stream the greeting straight from the LLM, token by token.

        Same prompt as _generate_greeting, but a true stream: nothing is held
        back or replayed. The full text is yielded as it is generated so the
        caller can (a) accumulate it for the history and (b) forward each
        token to the client.
        """
        from app.ai.llm_engine import _get_groq_client
        import asyncio as _asyncio

        doctor = session.doctor_profile
        if mode == ConversationMode.TRAINING:
            situation = (
                f"This is a TRAINING simulation. You play ALIA, virtual representative of VITAL SA, "
                f"opening a visit with a simulated doctor: {doctor.name}, {doctor.specialty}, "
                f"communication style '{doctor.style.value}'. The trainee (a sales rep) is practicing. "
                f"This is the INTRODUCTION only: greet him, introduce yourself in one sentence, then "
                f"invite HIM to introduce himself (who he is, which laboratory he represents, his "
                f"role) and stop there. Do NOT ask anything about his practice, his patients, his "
                f"needs or the product — the first question of the visit comes only after he has "
                f"introduced himself. 2-3 sentences max, in French. "
                f"Never use placeholders like [Votre Nom] - just speak as ALIA.")
        else:
            situation = (
                f"You are ALIA, virtual representative of VITAL SA, opening a commercial visit with "
                f"Dr {doctor.name} ({doctor.specialty}). Introduce yourself and ask for 2 minutes of "
                f"their time. 2-3 sentences max, in French."
            )

        messages = [
            {"role": "system", "content": situation},
            {"role": "user", "content": "(The visit is starting - deliver your opening line.)"},
        ]

        client = _get_groq_client()
        if not client:
            raise RuntimeError("Groq client not initialized")

        candidates = [get_settings().GROQ_MODEL] + self.llm.GROQ_FALLBACK_MODELS
        last_error: Optional[Exception] = None
        for model in dict.fromkeys(candidates):
            try:
                stream = await _asyncio.to_thread(
                    lambda m=model: client.chat.completions.create(
                        model=m,
                        messages=messages,
                        temperature=0.9,
                        max_tokens=180,
                        stream=True,
                    )
                )
                produced = False
                for chunk in stream:
                    delta = chunk.choices[0].delta if chunk.choices else None
                    piece = (getattr(delta, "content", None) or "") if delta else ""
                    if piece:
                        produced = True
                        yield piece
                if produced:
                    return
            except Exception as e:  # noqa: BLE001
                last_error = e
                logger.warning(f"Greeting stream failed on '{model}': {e}")
                continue
        raise RuntimeError(f"all greeting stream models failed: {last_error}")

    async def send_message_stream(self, request: ConversationRequest) -> AsyncIterator[str]:
        """Stream ALIA's reply token by token for one user message.

        Mirrors the bookkeeping of send_message (intent, history, step advance)
        but yields LLM tokens as they arrive instead of one finished string.
        No canned responses: when the LLM fails, the generator raises and the
        caller sends an error frame - nothing is invented.
        """
        session_id = request.session_id

        if not session_id or session_id not in self.sessions:
            start_req = StartSessionRequest(
                mode=request.mode,
                product_focus=request.product_focus,
                doctor_profile=request.doctor_profile,
                level=request.level,
                visit_format=request.visit_format,
            )
            start_resp = await self.start_session(start_req)
            session_id = start_resp.session_id

        session = self.sessions[session_id]
        flow = self.flows[session_id]
        history = self.conversation_histories[session_id]

        # Sync the live countdown so the doctor paces his Q&A per step.
        if request.time_elapsed:
            session.time_elapsed = request.time_elapsed
        if request.time_budget:
            session.time_budget = request.time_budget

        intent = self.llm.detect_intent(request.message)
        sentiment = self.llm.detect_sentiment(request.message)

        user_msg = ConversationMessage(
            role="user",
            content=request.message,
            step=session.current_step,
            intent=intent,
            sentiment=sentiment,
        )
        session.messages.append(user_msg)
        history.append({"role": "user", "content": request.message})

        rag_context = rag_pipeline.build_rag_context(product_focus=session.product_focus)

        # Stream the reply; every token goes straight to the caller.
        pieces: List[str] = []
        async for token in self.llm.generate_response_stream(
            session=session,
            user_message=request.message,
            rag_context=rag_context,
            conversation_history=history,
        ):
            pieces.append(token)
            yield token

        ai_response = "".join(pieces)

        # Step advancement is MANUAL: the user clicks "Étape suivante".
        # track_interaction only - no should_advance_step / advance_step here.
        flow.track_interaction(request.message, ai_response, intent)
        ai_msg = ConversationMessage(
            role="assistant",
            content=ai_response,
            step=session.current_step,
            metadata={"intent": intent.value, "sentiment": sentiment.value, "flow_state": flow.get_flow_state()},
        )
        session.messages.append(ai_msg)
        history.append({"role": "assistant", "content": ai_response})

    async def set_step(self, session_id: str, target: str, time_elapsed: int = 0, time_budget: int = 0) -> VisitStep:
        """Jump the visit to a given step (time-driven progression)."""
        flow = self.flows.get(session_id)
        if not flow:
            raise KeyError(f"Unknown session {session_id}")
        session = self.sessions[session_id]
        if time_elapsed:
            session.time_elapsed = time_elapsed
        if time_budget:
            session.time_budget = time_budget
        try:
            step = VisitStep(target)
        except ValueError:
            raise ValueError(f"Unknown step '{target}'")
        session.current_step = step
        logger.info(f"Step set to {step.value} from the visit timer")
        return step

    async def advance_step_manual(self, session_id: str, time_elapsed: int = 0, time_budget: int = 0) -> VisitStep:
        """Manually advance the visit step (user clicked 'Étape suivante').

        Also syncs the live time budget so the doctor paces his Q&A.
        """
        flow = self.flows.get(session_id)
        if not flow:
            raise KeyError(f"Unknown session {session_id}")
        session = self.sessions[session_id]
        if time_elapsed:
            session.time_elapsed = time_elapsed
        if time_budget:
            session.time_budget = time_budget
        return flow.advance_step()

    async def send_message(self, request: ConversationRequest) -> ConversationResponse:
        """Process a user message and return ALIA's response."""
        session_id = request.session_id

        # Create session if needed
        if not session_id or session_id not in self.sessions:
            start_req = StartSessionRequest(
                mode=request.mode,
                product_focus=request.product_focus,
                doctor_profile=request.doctor_profile,
                level=request.level,
                visit_format=request.visit_format,
            )
            start_resp = await self.start_session(start_req)
            session_id = start_resp.session_id

        session = self.sessions[session_id]
        flow = self.flows[session_id]
        history = self.conversation_histories[session_id]

        # Detect intent and sentiment
        intent = self.llm.detect_intent(request.message)
        sentiment = self.llm.detect_sentiment(request.message)

        # Track the interaction
        flow.track_interaction(request.message, "", intent)

        # Add user message to history
        user_msg = ConversationMessage(
            role="user",
            content=request.message,
            step=session.current_step,
            intent=intent,
            sentiment=sentiment,
        )
        session.messages.append(user_msg)
        history.append({"role": "user", "content": request.message})

        # Step advancement is MANUAL (user clicks 'Étape suivante').

        # Get RAG context
        rag_context = rag_pipeline.build_rag_context(product_focus=session.product_focus)

        # Get step-specific system instructions
        step_instructions = flow.get_system_prompt_for_step()

        # Generate ALIA's response (streaming is exposed separately; the
        # non-streaming path stays for the REST endpoint and scoring).
        ai_response = self.llm.generate_response(
            session=session,
            user_message=request.message,
            rag_context=rag_context,
            conversation_history=history,
        )

        # Track the response
        flow.track_interaction(request.message, ai_response, intent)

        # Add AI response to history
        ai_msg = ConversationMessage(
            role="assistant",
            content=ai_response,
            step=session.current_step,
            metadata={
                "intent": intent.value,
                "sentiment": sentiment.value,
                "flow_state": flow.get_flow_state(),
            },
        )
        session.messages.append(ai_msg)
        history.append({"role": "assistant", "content": ai_response})

        # Calculate score update
        score_update = self.scorer.get_running_score(flow)

        return ConversationResponse(
            session_id=session_id,
            message=ai_response,
            current_step=session.current_step,
            metadata={
                "intent": intent.value,
                "sentiment": sentiment.value,
                "flow_state": flow.get_flow_state(),
            },
            score_update=score_update,
        )

    async def _complete_session(self, session: VisitSession, flow: VisitFlowEngine, session_id: str) -> ConversationResponse:
        """Handle session completion."""
        # Score the session
        scoring_result = self.scorer.score_session(session, flow)

        # Generate CRM report
        report = self.scorer.generate_crm_report(session, flow, scoring_result)

        # Generate completion message
        completion_msg = self._generate_completion_message(scoring_result, report)

        # Add to history
        ai_msg = ConversationMessage(
            role="assistant",
            content=completion_msg,
            step=VisitStep.COMPLETED,
            metadata={
                "scoring": scoring_result.model_dump(),
                "crm_report": report.model_dump(),
            },
        )
        session.messages.append(ai_msg)
        session.ended_at = datetime.now()
        session.scores = {
            "overall": scoring_result.overall_score,
            **scoring_result.step_scores,
        }

        self.conversation_histories[session_id].append({"role": "assistant", "content": completion_msg})

        return ConversationResponse(
            session_id=session_id,
            message=completion_msg,
            current_step=VisitStep.COMPLETED,
            metadata={
                "scoring": scoring_result.model_dump(),
                "crm_report": report.model_dump(),
            },
            score_update={"overall": scoring_result.overall_score},
        )

    def get_session(self, session_id: str) -> Optional[VisitSession]:
        """Get a session by ID."""
        return self.sessions.get(session_id)

    def get_all_sessions(self) -> List[VisitSession]:
        """Get all sessions."""
        return list(self.sessions.values())

    def get_session_history(self, session_id: str) -> List[Dict[str, str]]:
        """Get conversation history for a session."""
        return self.conversation_histories.get(session_id, [])

    # ──────────────────────────────────────────────
    # Greeting (LLM-generated, no canned script)
    # ──────────────────────────────────────────────

    async def _generate_greeting(self, session: VisitSession, mode: ConversationMode) -> str:
        """ALIA's opening line, generated by the LLM from the session context.

        The prompt fixes only the facts (who ALIA is, the doctor's profile,
        the goal) — the wording is entirely the model's, so no two greetings
        are identical and nothing is hardcoded.
        """
        doctor = session.doctor_profile
        if mode == ConversationMode.TRAINING:
            situation = (
                f"This is a TRAINING simulation. You play ALIA, virtual representative of VITAL SA, "
                f"opening a visit with a simulated doctor: {doctor.name}, {doctor.specialty}, "
                f"communication style '{doctor.style.value}'. The trainee (a sales rep) is practicing. "
                f"This is the INTRODUCTION only: greet him, introduce yourself in one sentence, then "
                f"invite HIM to introduce himself (who he is, which laboratory he represents, his "
                f"role) and stop there. Do NOT ask anything about his practice, his patients, his "
                f"needs or the product — the first question of the visit comes only after he has "
                f"introduced himself. 2-3 sentences max, in French. "
                f"Never use placeholders like [Votre Nom] - just speak as ALIA.")
        else:
            situation = (
                f"You are ALIA, virtual representative of VITAL SA, opening a commercial visit with "
                f"Dr {doctor.name} ({doctor.specialty}). Introduce yourself and ask for 2 minutes of "
                f"their time. 2-3 sentences max, in French."
            )

        messages = [
            {"role": "system", "content": situation},
            {"role": "user", "content": "(The visit is starting - deliver your opening line.)"},
        ]

        try:
            from app.ai.llm_engine import _get_groq_client
            client = _get_groq_client()
            if not client:
                raise RuntimeError("Groq client not initialized")
            import asyncio as _asyncio

            # Same candidate chain as the engine (the configured model may be
            # stale; the fallback list carries a known-good one).
            candidates = [get_settings().GROQ_MODEL] + self.llm.GROQ_FALLBACK_MODELS
            text = ""
            for model in dict.fromkeys(candidates):  # dedupe, keep order
                try:
                    response = await _asyncio.to_thread(
                        lambda m=model: client.chat.completions.create(
                            model=m,
                            messages=messages,
                            temperature=0.9,
                            max_tokens=180,
                        )
                    )
                    text = (response.choices[0].message.content or "").strip()
                    if text:
                        break
                except Exception as inner:  # noqa: BLE001
                    logger.warning(f"Greeting model '{model}' failed: {inner}")
            if text:
                return text
            raise RuntimeError("all greeting models failed")
        except Exception as e:  # noqa: BLE001
            # No hardcoded greeting: rethrow - the API layer surfaces the error
            # and the frontend shows it, instead of a canned script.
            logger.error(f"LLM greeting failed: {e}")
            raise

    async def send_message_stream(self, request: "ConversationRequest") -> AsyncIterator[str]:
        """Stream ALIA's reply token by token for one user message.

        Mirrors the bookkeeping of send_message (intent, history, step advance)
        but yields LLM tokens as they arrive instead of one finished string.
        No canned responses: when the LLM fails, the generator raises and the
        caller sends an error frame - nothing is invented.
        """
        session_id = request.session_id

        if not session_id or session_id not in self.sessions:
            start_req = StartSessionRequest(
                mode=request.mode,
                product_focus=request.product_focus,
                doctor_profile=request.doctor_profile,
                level=request.level,
                visit_format=request.visit_format,
            )
            start_resp = await self.start_session(start_req)
            session_id = start_resp.session_id

        session = self.sessions[session_id]
        flow = self.flows[session_id]
        history = self.conversation_histories[session_id]

        intent = self.llm.detect_intent(request.message)
        sentiment = self.llm.detect_sentiment(request.message)

        user_msg = ConversationMessage(
            role="user",
            content=request.message,
            step=session.current_step,
            intent=intent,
            sentiment=sentiment,
        )
        session.messages.append(user_msg)
        history.append({"role": "user", "content": request.message})

        rag_context = rag_pipeline.build_rag_context(product_focus=session.product_focus)

        # Stream the reply; every token goes straight to the caller.
        pieces: List[str] = []
        async for token in self.llm.generate_response_stream(
            session=session,
            user_message=request.message,
            rag_context=rag_context,
            conversation_history=history,
        ):
            pieces.append(token)
            yield token

        ai_response = "".join(pieces)

        # Step advancement is MANUAL (user clicks 'Étape suivante').
        flow.track_interaction(request.message, ai_response, intent)
        ai_msg = ConversationMessage(
            role="assistant",
            content=ai_response,
            step=session.current_step,
            metadata={"intent": intent.value, "sentiment": sentiment.value, "flow_state": flow.get_flow_state()},
        )
        session.messages.append(ai_msg)
        history.append({"role": "assistant", "content": ai_response})

    def _generate_completion_message(self, scoring_result, report) -> str:
        """Generate session completion message with scoring."""
        return (
            f"✅ **Visite Terminée !**\n\n"
            f"**Score Global:** {scoring_result.overall_score:.1f}/10\n\n"
            f"**Scores par étape:**\n"
            + "\n".join([f"  • {step}: {score:.1f}/10" for step, score in scoring_result.step_scores.items()])
            + f"\n\n**Points Forts:**\n"
            + "\n".join([f"  ✅ {s}" for s in scoring_result.strengths])
            + f"\n\n**Axes d'Amélioration:**\n"
            + "\n".join([f"  📝 {s}" for s in scoring_result.areas_for_improvement])
            + f"\n\n**Rapport CRM Généré:**\n"
            f"  Durée: {report.duration_seconds}s | Format: {report.visit_format.value}\n"
            f"  Besoin identifié: {report.need_identified}\n"
            f"  Message délivré: {report.message_delivered}\n"
            f"  Prochaine action: {report.next_step}"
        )


# Global instance
orchestrator = ConversationOrchestrator()
